name: cicd

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      solutionPath: .\src
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change this to your preferred .NET version

    - name: Build
      run: dotnet build ${{env.solutionPath}} -c Release

    - name: Test
      run: dotnet test ${{env.solutionPath}}

  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change this to your preferred .NET version

    - name: Create NuGet package
      run: dotnet pack ${{env.solutionPath}} -c Release --include-symbols -o ./nuget

    - name: Publish to NuGet
      uses: nuget/push@v0.8.4
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}  # Set NUGET_API_KEY as a secret in your repository
        nuget-spec: './**/*.nupkg'
        version: 'latest'